import { Content } from "@shared/schema";

export const contentData: Content[] = [
  {
    id: "1",
    type: "movie",
    title: "LOS INCREÍBLES",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 99,
    hypeLevel: 98,
    releaseDate: "2017-05-15",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "2h 23m"
  },
  {
    id: "2",
    type: "movie",
    title: "LOS INCREÍBLES 2",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 85,
    hypeLevel: 91,
    releaseDate: "2018-07-19",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "2h 12m"
  },
  {
    id: "3",
    type: "movie",
    title: "LOS INCREÍBLES 3",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 91,
    hypeLevel: 89,
    releaseDate: "2018-01-15",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "2h 35m"
  },
  {
    id: "4",
    type: "movie",
    title: "LOS INCREÍBLES 4",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 75,
    hypeLevel: 82,
    releaseDate: "2019-09-20",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "1h 45m"
  },
  {
    id: "5",
    type: "movie",
    title: "LOS INCREÍBLES 5",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 99,
    hypeLevel: 93,
    releaseDate: "2020-03-25",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "2h 53m"
  },
  {
    id: "6",
    type: "movie",
    title: "LOS INCREÍBLES 6",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 42,
    hypeLevel: 75,
    releaseDate: "2021-06-12",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "2h 23m"
  },
  {
    id: "7",
    type: "movie",
    title: "LOS INCREÍBLES 7",
    description: "Los Increibles son un equipo de individuos extraordinarios, con superpoderes u otras características especiales. Aunque su principal objetivo es defender los intereses de Estados Unidos , el propósito del grupo es proteger la estabilidad global de amenazas internas o extraterrestres.",
    category: "Ciencia Ficción",
    qualityRating: 98,
    hypeLevel: 95,
    releaseDate: "2022-02-20",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/Los_Increaibles-939387273-large.jpg",
    duration: "2h 45m"
  },
  {
    id: "8",
    type: "movie",
    title: "IT: CHAPTER I",
    description: "Varios niños de una pequeña ciudad del estado de Maine se alían para combatir a una entidad diabólica que adopta la forma de un payaso y desde hace mucho tiempo emerge cada 27 años para saciarse de sangre infantil.",
    category: "Acción",
    qualityRating: 52,
    hypeLevel: 49,
    releaseDate: "2022-02-20",
    director: "Scott Cawtton",
    cast: ["Bill Skarsgård", "Jaeden Martell", "Finn Wolfhard..."],
    production: "Scott Movies",
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/5/5a/It_%282017%29_poster.jpg",
    duration: "2h 15m"
  },
  {
    id: "9",
    type: "movie",
    title: "BIG HERO 6",
    description: "Cuando un giro inesperado de eventos los sumerge en el medio de un peligroso plan, un niño prodigio, su robot y sus amigos se convierten en héroes de alta tecnología en una misión para salvar su ciudad.",
    category: "Aventura",
    qualityRating: 70,
    hypeLevel: 53,
    releaseDate: "2023-06-15",
    director: "Don Hall",
    cast: ["Bill Skarsgård", "Jaeden Martell", "Finn Wolfhard..."],
    production: "Scott Cawtton, Disney+, Pixar Animation Studios",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgO09Dz477T1FRQFoozJ8JOtMs7lE3_WI1NyHO_YIb6tW-N2rsjP_6DvSwZd-zUGHQbK4C8TFSPtyjwyjRJu2un_W1WEnvFRFADMV03Q&s=10",
    duration: "1h 42m"
  },
  {
    id: "10",
    type: "movie",
    title: "CARS",
    description: "De camino al prestigiado campeonato Copa Pistón, un automóvil de carreras que sólo se preocupa por ganar aprende sobre lo que realmente es importante en la vida de varios vehículos que viven en un pueblo a lo largo de la histórica Ruta 66.",
    category: "Aventura",
    qualityRating: 98,
    hypeLevel: 97,
    releaseDate: "2023-08-25",
    director: "John Lasseter",
    cast: ["Owen Wilson", "Bonnie Hunt", "Paul Newman..."],
    production: "Pixar Animation Studios",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCnBYAFjzBoVrL-AIcV3jQ7PJbTOaoAzctAiq-M9rY5RlDjRGOYDzyUIGMPkJrTZudA47OgmIRNY3PGogxQzkmUM_mTvDF3FfQCDIZMw&s=10",
    duration: "1h 57m"
  },
  {
    id: "11",
    type: "movie",
    title: "IT: CHAPTER TWO",
    description: "En el misterioso pueblo de Derry, un payaso llamado Pennywise vuelve 27 años después para atormentar a los ahora adultos miembros del Club de los Perdedores, que se encuentran alejados unos de otros.",
    category: "Terror",
    qualityRating: 45,
    hypeLevel: 35,
    releaseDate: "2023-12-01",
    director: "Scott Cawtton",
    cast: ["Bill Skarsgård", "Jaeden Martell", "Finn Wolfhard..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/It_Capaitulo_2-844935737-mmed.jpg",
    duration: "2h 49m"
  },
  {
    id: "12",
    type: "movie",
    title: "IT: CHAPTER THREE",
    description: "En el misterioso pueblo de Derry, un payaso llamado Pennywise vuelve 27 años después para atormentar a los ahora adultos miembros del Club de los Perdedores, que se encuentran alejados unos de otros.",
    category: "Terror",
    qualityRating: 66,
    hypeLevel: 29,
    releaseDate: "2024-02-15",
    director: "Scott Cawtton",
    cast: ["Bill Skarsgård", "Jaeden Martell", "Finn Wolfhard..."],
    production: "Scott Movies",
    posterUrl: "https://pics.filmaffinity.com/It_Capaitulo_2-844935737-mmed.jpg",
    duration: "2h 35m"
  },
  {
    id: "13",
    type: "movie",
    title: "LOS INCREÍBLES 8",
    description: "Los Increibles comprenden por fin lo frágil que es la realidad y los sacrificios que hay que hacer para mantenerla, en una historia de amistad, trabajo en equipo y sobre dejar a un lado las diferencias para superar un obstáculo imposible.",
    category: "Ciencia Ficción",
    qualityRating: 99,
    hypeLevel: 99,
    releaseDate: "2024-05-01",
    director: "Scott Cawtton",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "Scott Movies, Marvel Studios, Pixar Animation Studios, Disney+",
    posterUrl: "https://es.web.img3.acsta.net/pictures/18/04/13/11/46/5802807.jpg",
    duration: "3h 10m"
  },
  {
    id: "14",
    type: "movie",
    title: "CARS 2",
    description: "El Rayo McQueen y Mate viajan a Japón para participar en una carrera patrocinada por los fabricantes de un tipo de combustible ecológico. Sin embargo, unos villanos pretenden que el nuevo producto fracase.",
    category: "Aventura",
    qualityRating: 90,
    hypeLevel: 86,
    releaseDate: "2024-06-15",
    director: "John Lasseter",
    cast: ["Owen Wilson", "Bonnie Hunt", "Paul Newman..."],
    production: "Pixar Animation Studios",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMTUzNTc3MTU3M15BMl5BanBnXkFtZTcwMzIxNTc3NA@@._V1_FMjpg_UX1000_.jpg",
    duration: "1h 46m"
  },
  {
    id: "15",
    type: "movie",
    title: "CARS 3",
    description: "Eclipsado por los autos jóvenes, el veterano Rayo McQueen ha sido expulsado del deporte que tanto ama. Sin embargo, no se rendirá tan fácilmente, con la ayuda de sus amigos, Rayo aprende trucos nuevos para vencer al arrogante Jackson Storm, el rival que lo humilló.",
    category: "Aventura",
    qualityRating: 92,
    hypeLevel: 79,
    releaseDate: "2024-12-10",
    director: "Brian Fee",
    cast: ["Owen Wilson", "Bonnie Hunt", "Paul Newman..."],
    production: "Pixar Animation Studios",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq7ZkiSXOjQnuEjUQhF4so6LTdRgoOhpHzLYO3LlAY0QPk9CQ6xpXIxJ5yruFJ4oTqYKUcNd2Uqb-OaZ3_VzBbfy6Vk4gftiiyBUQewg&s=10",
    duration: "1h 49m"
  },
  {
    id: "16",
    type: "movie",
    title: "TOY STORY",
    description: "Woody, el juguete favorito de Andy, se siente amenazado por la inesperada llegada de Buzz Lightyear, el guardián del espacio.",
    category: "Comedia",
    qualityRating: 98,
    hypeLevel: 85,
    releaseDate: "2024-04-12",
    director: "John Lasseter",
    cast: ["Sheriff Woody", "Buzz Lightyear", "Sid Phillips..."],
    production: "Pixar Animation Studios",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa23ZtIVnvhYnj2xCz0emBJn3qY6Vjp8M-lQ&s",
    duration: "1h 21m"
  },
  {
    id: "17",
    type: "movie",
    title: "Rapidos & Furiosos",
    description: "Fast & Furious es una franquicia de medios estadounidense centrada en una serie de películas de acción que se ocupan en gran medida de automóviles. La saga también incluye cortometrajes, una serie de televisión, espectáculos en vivo, videojuegos y atracciones de parques temáticos",
    category: "Acción",
    qualityRating: 90,
    hypeLevel: 80,
    releaseDate: "2024-06-17",
    director: "Vin Diesel",
    cast: ["Vin Diesel", "Paul Walker", "Michelle Rodriguez..."],
    production: "Scott Movies",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZDU0Yjk5MTctZDI3OS00YmM4LWIxOTMtYTU2NjYyYzdkMWJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    duration: "2h 20m"
  },
  {
    id: "18",
    type: "movie",
    title: "Five Nights At Freddy's: The Movie",
    description: "Un problemático guardia de seguridad empieza a trabajar en la pizzería Freddy Fazbear's. Mientras pasa su primera noche en el trabajo, se da cuenta de que el turno de noche va a resultar aterrador.",
    category: "Terror",
    qualityRating: 96,
    hypeLevel: 97,
    releaseDate: "2023-10-27",
    director: "Emma Tammi",
    cast: ["Josh Hutcherson", "Matthew Lillard", "Elizabeth Lail..."],
    production: "Scott Movies",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ1yswkInbGnbsmaPXv4xZF9a9qNB3Ic9z42NrcLqNnPzb3vrlkD87XnzzISle5eElsFIhKLBeEtKRxdPdgy6SVDTVT5g1jGKrcPYlsRY&s=10",
    duration: "1h 50m"
  },
  {
    id: "19",
    type: "series",
    title: "LOS INCREIBLES: CORTOS",
    description: "Un equipo élite de investigadores utiliza tecnología de punta para resolver los crímenes más complejos. Cada episodio revela nuevas capas de una conspiración masiva.",
    category: "Comedia",
    qualityRating: 80,
    hypeLevel: 65,
    releaseDate: "2023-01-01",
    director: "Scott Movies",
    cast: ["Chris Hemsworth", "Robert Downey Jr.", "Tom Hiddleston..."],
    production: "PrimeCrime Network",
    posterUrl:"https://i.pinimg.com/originals/8d/57/0c/8d570ca81ea7fe12772fa784c1fc6d72.jpg",
    seasons: 1
  },
  {
    id: "20",
    type: "series",
    title: "THE PROJECT X",
    description: "Tres estudiantes de secundaria deciden organizar una fiesta salvaje en casa de uno de ellos, aprovechando que sus padres no están. Quieren hacer que la fiesta sea inolvidable, así que deciden grabarlo todo",
    category: "Comedia",
    qualityRating: 91,
    hypeLevel: 86,
    releaseDate: "2024-03-15",
    director: "Scott Cawtton",
    cast: ["SGustinPROD", "Dax Flame", "Alexis Knapp", "Miles Teller"],
    production: "Scott Movies, Warner, Illumination, SGustin Music",
    posterUrl: "https://images.justwatch.com/poster/100745974/s718/project-x.jpg",
    seasons: 3
  },
  {
    id: "21",
    type: "series",
    title: "Judy",
    description: "Frances Ethel Gumm, conocida artísticamente como Judy Garland, fue una actriz y cantante estadounidense. Si bien fue aclamada por la crítica por muchos papeles diferentes a lo largo de su carrera, es ampliamente conocida por interpretar el papel de Dorothy Gale en El mago de Oz.",
    category: "Drama",
    qualityRating: 90,
    hypeLevel: 92,
    releaseDate: "2024-09-25",
    director: "Scott Cawtton",
    cast: ["Renée Zellweger"],
    production: "Scott Movies",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BYjY1OTJlZmQtNTEwNy00MjI1LWE4MWQtMzJlNTZmN2FmN2U5XkEyXkFqcGc@._V1_.jpg",
    seasons: 2
  },
  {
    id: "22",
    type: "series",
    title: "Bajo el mismo cielo",
    description: "Un contratista militar se encuentra en una encrucijada amorosa mientras trabaja en Hawái. Por un lado, Tracy, un viejo amor. Y por el otro, Allison, una dura piloto con la que conecta totalmente. Mientras su misión avanza, Tracy le desvelará algo trascendental acerca de su pasado.",
    category: "Drama",
    qualityRating: 82,
    hypeLevel: 76,
    releaseDate: "2024-08-12",
    director: "Scott Cawtton",
    cast: ["Emma Stone", "Tom Hiddleston"],
    production: "Scott Movies",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYqxIneiVotyqGHMisTMkmWr0dl_37wUddhqHwBMNz-gJhlsnU20w3RqbFYzHcwf1MpmsPZ8R-zkfLxz7J3OGYVsvqMTQI4SACJKKIeOc&s=10",
    seasons: 2
  },
  {
    id: "23",
    type: "series",
    title: "Zecko The Hacker",
    description: "Zecko es un joven inmigrante ucraniano que ayuda a sus padres realizando trabajos ilegales en Internet.",
    category: "Drama",
    qualityRating: 56,
    hypeLevel: 23,
    releaseDate: "2024-03-20",
    director: "Scott Cawtton",
    cast: ["Lorraine Nicholson"],
    production: "Scott Movies",
    posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnuGb-ukZK77lkhsm2X-rX-PhyLFJz41LDyw&s",
    seasons: 1
  },
  {
    id: "24",
    type: "series",
    title: "Gravity Falls",
    description: "Zecko es un joven inmigrante ucraniano que ayuda a sus padres realizando trabajos ilegales en Internet.",
    category: "Drama",
    qualityRating: 99,
    hypeLevel: 97,
    releaseDate: "2024-11-06",
    director: "Alex Hirsch, Shion Takeuchi, Josh Weinstein, Aury Wallington, Mark Rizzo",
    cast: ["Dipper Pains", "Mabel Pines", "Stan Pines"],
    production: "Scott Movies, Disney+",
    posterUrl: "https://es.web.img2.acsta.net/pictures/15/02/09/09/50/131883.jpg",
    seasons: 2
  },
  {
    id: "25",
    type: "series",
    title: "Squid Game",
    description: "Un grupo de 456 personas en bancarrota que aceptan participar en juegos infantiles secretos por una enorme suma de dinero. Sin embargo, los concursantes pronto descubren que los juegos son mortales: si pierden, mueren.",
    category: "Thriller",
    qualityRating: 98,
    hypeLevel: 96,
    releaseDate: "2024-09-25",
    director: "Hwang Dong-hyuk",
    cast: ["Jo Yu-ri", "Gong Yoo", "Lee Jung-jae"],
    production: "Scott Movies, Netflix",
    posterUrl: "https://media.themoviedb.org/t/p/w500/9PgvLKv0vSnJnCAhy3EivGTtHzF.jpg",
    seasons: 1
  },
  {
    id: "26",
    type: "series",
    title: "Peaky Blinders",
    description: "Gran Bretaña vive la posguerra. Los soldados regresan, se acuñan nuevas revoluciones y nacen bandas criminales en una nación agitada. En Birmingham, una pandilla de gánsters callejeros asciende hasta convertirse en los reyes de la clase obrera.",
    category: "Drama",
    qualityRating: 97,
    hypeLevel: 95,
    releaseDate: "2022-12-20",
    director: "Steven Knight, Toby Finlay, Stephen Russell",
    cast: ["Cillian Murphy", "Paul Anderson", "Tom Hardy"],
    production: "Scott Movies, Netflix",
    posterUrl: "https://imusic.b-cdn.net/images/item/original/825/5051561037825.jpg?peaky-blinders-2013-peaky-blinders-dvd&class=scaled&v=1382308494",
    seasons: 1
  },
  {
    id: "27",
    type: "movie",
    title: "Búsqueda implacable",
    description: "El exagente de las fuerzas especiales de élite Bryan Millis se ve enredado en la trama de una organización criminal cuando intenta salvar a su hija Kim, pero solo tiene 96 horas para rescatarla antes de perder el rastro.",
    category: "Drama",
    qualityRating: 77,
    hypeLevel: 95,
    releaseDate: "2025-11-04",
    director: "Pierre Morel",
    cast: ["Liam Neeson", "Maggie Grace", "Famke Janssen..."],
    production: "Netflix",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNzgwN2YzNjEtZjA2ZC00YTE1LWI4ZjEtZmFlNGU5MmIxNzFjXkEyXkFqcGc@._V1_.jpg",
    duration: "1h 33m"
  },
  {
    id: "28",
    type: "movie",
    title: "Toy Story 2",
    description: "Cuando Andy se va de campamento dejando solos a los juguetes, Al McWhiggin, un compulsivo coleccionista de juguetes valiosos, secuestra a Woody. Buzz Lightyear y los demás juguetes tendrán que actuar con rapidez si quieren rescatarlo. Durante la operación de rescate no sólo tendrán que afrontar múltiples peligros, sino que también vivirán divertidas situaciones.",
    category: "Aventura",
    qualityRating: 92,
    hypeLevel: 90,
    releaseDate: "2025-11-07",
    director: "John Lasseter",
    cast: ["Sheriff Woody", "Buzz Lightyear"],
    production: "Pixar Animation Studios",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BNzVmODlhMDEtY2YxZi00OTVjLTlkNTktN2Q2OTRlM2I4M2FhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    duration: "1h 33m"
  },
  {
    id: "29",
    type: "movie",
    title: "Actividad Paranormal",
    description: "Ryan y Emily se mudan a una nueva casa junto a su hija Leila, de 7 años. Allí encuentran una misteriosa cámara de vídeo que graba extrañas presencias. Además, Leila comienza a hablar con un amigo imaginario y a comportarse de forma desconcertante. Todo esto es el inicio de una pesadilla hecha realidad, ya que una entidad maligna y sobrenatural comienza a aterrorizarlos.",
    category: "Horror",
    qualityRating: 74,
    hypeLevel: 82,
    releaseDate: "2025-11-15",
    director: "Gregory Plotkin",
    cast: ["Katie Featherston", "Micah Sloat"],
    production: "Blumhouse Productions",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BMjY1NjcxODQ4MV5BMl5BanBnXkFtZTcwMzUxNjM4Mg@@._V1_FMjpg_UX1000_.jpg",
    duration: "1h 26m"
  },
  {
    id: "30",
    type: "series",
    title: "Stranger Things",
    description: "un grupo de amigos en el pueblo de Hawkins, Indiana, en los años 80, que se enfrentan a fuerzas sobrenaturales y a experimentos secretos del gobierno tras la misteriosa desaparición de uno de ellos",
    category: "Horror",
    qualityRating: 95,
    hypeLevel: 90,
    releaseDate: "2025-11-17",
    director: "Matt Duffer, Ross Duffer, Kate Trefry, Justin Doble, Paul Dichter, Jessie Nickson-Lopez",
    cast: ["Millie Bobby Brown", "Finn Wolfhard..."],
    production: "Netflix",
    posterUrl: "https://static.wikia.nocookie.net/netflix9203/images/1/12/Stranger_Things.png/revision/latest?cb=20200901053540&path-prefix=es",
    seasons: 1
  },
  {
    id: "31",
    type: "movie",
    title: "Five Nights At Freddy's: The Movie",
    description: "Five Nights at Freddy's 2 es una película de terror sobrenatural estadounidense de 2025 basada en la serie de videojuegos Five Nights at Freddy's de Scott Cawthon, y la secuela de Five Nights at Freddy's.​ La película está dirigida por Emma Tammi y escrita por Cawthon.",
    category: "Terror",
    qualityRating: 91,
    hypeLevel: 98,
    releaseDate: "2024-12-05",
    director: "Emma Tammi",
    cast: ["Josh Hutcherson", "Matthew Lillard", "Elizabeth Lail..."],
    production: "Scott Movies",
    posterUrl: "https://m.media-amazon.com/images/M/MV5BZmQ3NmIxNTgtYjFiNS00NzliLWI0YzAtZDkxY2E0YWIxZDEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    duration: "1h 44m"
  },
];
